# 配置项目端口号
server: 8080
# 连接数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?characterEncoding=utf8mb4&useSSL=true
    name: root
    password: 1234
# 自定义配置项
csdn.token: xxx

string1: 你好\n世界
string2: '你好\n世界'
string3: "你好\n世界"

# 对象写法1
student:
  id: 1
  name: 张三
  age: 18

# 对象写法2
student2: { id: 2,name: 李四,age: 20 }

# 集合写法1
dbtypes:
  name:
    - mysql
    - sqlserver
    - db2
# 集合写法2
dbtypes2: {name: [mysql,sqlserver,db2]}